midudev/miduconf-website

astro.config.mjs
src/components/TextWithDegradation.astro
src/components/WindowButton.astro
tailwind.config.js

Configuration and definition of custom colors

---

src/components/HomeSpeakers.astro
src/components/HomeSponsors.astro

change the vertical padding of section for a better visualization at transitions from nav

style: change the vertical padding of sections

---

src/components/Header.astro

with this change, its possible go back to the home page from others pages

fix: modify the nav anchors for correct redirect

---

README.md

When user click on banner, this will redirect to miduconf's page

---

src/components/Button.astro
src/pages/ticket.astro

I added responsive and frame to ticket similar to ticket of vite conf.

Add responsive and frame ticket similar to vite conf 

---

package.json

script for clean and reinstall all repositories in windows

feat: new script phoenix-win for windows users

---

src/pages/ticket/[username].astro

feat: Added Home button to Ticket Page

---

src/components/Button.astro
src/components/FlavourTechs.astro
src/components/TicketButtons.astro
src/components/TicketCard.astro
src/components/TicketFlavours.astro
src/global.css
src/hooks/useShowNeededOptions.ts
src/pages/ticket/[username].astro
src/services/get-ticket.ts

- **Se corrige problema de UI al tener el tamaño de la fuente grande.**
Al tener la fuente del navegador en *large* o *very large*, el ticket se muestra así:
Así se muestra con los cambios de esta PR y la fuente en *large*:
(el *scrollbar* no se muestra con el tamaño de fuente por defecto, se muestra solo cuando es necesario)
- **Estilos en los botones de abajo del ticket.**
Antes:
Después:
- **`max-width` en container de los sabores.**
En pantallas `md`, el container de los sabores ocupaba el 100% del ancho de la pantalla, esto se corrigió añadiendo un `max-w-4xl`
Antes:
Después:
- **Los sabores del ticket se ordenan alfabéticamente**
- **El texto "Elige tu sabor de ticket" se modifica a "Elige el sabor de tu ticket"**
- **Se refactoriza `/pages/ticket/[username.astro]`**
```diff
+ …
```

Refactor and minimal improvements in ticket page

---

src/layouts/base.astro
src/pages/codigo-de-conducta.astro

Corrige el color de fondo en la página de código de conducta

---

src/components/Countdown.tsx
src/components/Principal.astro
src/hooks/useRemainingTime.ts

He añadido una cuenta atrás para el gran evento

feat: added a countdown to september 13th

---

src/components/Countdown.tsx
src/components/Principal.astro

Buenas!
usando la propiedad countdownEnded se modifica los literales
```tsx
<div class='mb-2 font-bold'>			
{!countdownEnded ? '¡Ya falta muy poco!' : 'Empieza la #miduConf 🎊'}
</div>

feat: countdownEnded used

---

src/components/Countdown.tsx
src/hooks/useRemainingTime.ts
src/utils/dates.ts

Antes el countdown estaba con la hora de Madrid, se modifica para el timezone del cliente
hice una función para utilizarla tambien en ScheduleItem.astro, pero no sé como usar una función importada, además me da errores el eslint

feat: added timezone to countdown

---

src/components/Principal.astro

issue -> https://github.com/midudev/miduconf-website/issues/78
gracias @marsidev

fix: iframe in mobile

---

src/styles/globals.css

fixing overflow for firefox browser

fix: overflow firefox

---

src/components/Speakers.tsx

Arreglé la URL de Twitter de nuestro amigo David y le quité el '@' a Nerea solo por buenas practicas. Abrazo grande Midu :)

David East and Nerea Luis twitter urls fixed

---

src/flavors/data.tsx

fix dimensions for JS and TS logos

---

src/flavors/data.tsx

Hola midudev 
Subo nuevo sabor de tailwind

ADD tailwind flavor

---

src/flavors/data.tsx

Flavor npm logo

---

src/flavors/data.tsx

Agregué el flavor de Ruby y le borré una linea a TypeScript que tenia el mismo atributo dos veces, (chequeé que funcione todo bien)

Add Ruby flavor

---

src/flavors/data.tsx

Adding Alpinejs flavor🎨

---

src/pages/ticket.js

La tenemos el 12 de septiembre y no el 13, qué ganicas, ¡Midu!

feat: change date in description ticket when sharing on twitter

---

src/sections/agenda.tsx
src/sections/gifts.tsx

Issue relacionado: https://github.com/midudev/miduconf-website/issues/146

feat: use a more generic word to avoid confusion in latam

---

src/components/Header.tsx

Open the discord invitation link on a new page

feat: Add target _blank for discord link

---

src/components/icons/languages/index.ts
src/components/icons/languages/pnpm.tsx
src/flavors/data.tsx

Create pnpm flavor

---

src/components/ReviewCard.tsx
src/components/Sponsor.tsx
src/sections/sponsors.tsx
src/styles/globals.css

- The sponsors section is restructured to group sponsors by level (diamond, premium, basic).
- A `ReviewCard` component is created for each sponsor level to display sponsors in a more flexible and scalable way.
- Appearance animation and bitmap effect are added to each sponsor's slogan on desktop (on mobile, all animation is removed and the slogan is shown as-is to avoid animation issues).
- Responsive styles and visual improvements are added for sponsor
https://github.com/user-attachments/assets/7f49efb4-c114-40cf-8402-d6d5e35e7753

Refactor and Animation of the Sponsors Section

---

src/components/Background3D.tsx
src/components/CallToAction.tsx
src/components/Header.tsx
src/components/experience/DitheringEffect.ts
src/components/experience/MiduLogo3D.tsx
src/sections/hero.tsx
src/styles/globals.css

- Nuevo componente Background3D con shader personalizado y reutilizando el dithering con postprocessing
- Se corrigio el problema del logo al presionar o al girar en el modelo
- Hero ahora muestra fondo 3D en desktop
https://github.com/user-attachments/assets/dab15555-b894-42c6-95e2-5026d2500c90
https://github.com/user-attachments/assets/f6140c83-17ac-48a5-9642-d41c960a7aa1

feat: add animated 3D background and improve dithering shader saturation and brightness

---

src/sections/faqs.tsx

- Added GSAP animations to the FAQs section for improved UX
- Enhanced interactive elements and smooth transitions
https://github.com/user-attachments/assets/cdb435bd-ec44-4544-a15b-ad560fb66f60

feat: enhance FAQs section with GSAP animations and improved structure

---

src/components/ReviewCard.tsx
src/components/Sponsor.tsx
src/sections/sponsors.tsx

This pull request refactors the sponsors section for better visual hierarchy and clarity.
Updates grid layout and spacing for improved responsiveness
Enhances sponsor card styles and removes scaling
Improves section text and highlights for better readability

Improve sponsors section layout and styles
